### ISSUE TITLE
vector には等値比較演算子がある

### ISSUE THREAD

**Issue by yaito3014** [Etising/cpp-library#17]
https://github.com/Etising/cpp-library/blob/3af5745b7623ba470897a06961b4012c98f26857/src/template.hpp#L74

`vsame`の存在理由とは？
https://cpprefjp.github.io/reference/vector/vector/op_equal.html

**Comment by Etising** [comment]
なんか昔うまくいかなくて作った記憶があるんですけど、確かにこれいらないですね...
