### ISSUE TITLE
[hex.hpp]to_d関数にstd::powを用いているため大きい値で誤差る

### ISSUE THREAD

**Issue by Etising** [Etising/cpp-library#19]
Epowで実装したいけど、template.hppをincludeすることになってしまう

**Comment by yaito3014** [comment]
欲しいのは与えられた基数を公比とする等比数列なので、 pow を用いなくとも変数を用意して for 文の内部で基数を掛けていけば良いのでは？

**Comment by Etising** [comment]
盲点でした、、、
ありがとうございます！
